//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PagedListTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public Nullable<int> Number { get; set; }
        public string order_date { get; set; }
        public Nullable<int> cust_id { get; set; }
        public int salesperson_id { get; set; }
        public int Amount { get; set; }
    }
}
